spring:
  datasource:
    url: jdbc:h2:mem:meanhwa-test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: always

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
