name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker build & push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t "$DOCKERHUB_USERNAME/meanhwa-back" .
          docker push "$DOCKERHUB_USERNAME/meanhwa-back"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_PEM_KEY }}
          envs: DOCKERHUB_USERNAME,DB_URL,DB_USERNAME,DB_PASSWORD
          script: |
            sudo docker pull "$DOCKERHUB_USERNAME/meanhwa-back"
            sudo docker stop meanhwa-server || true
            sudo docker rm meanhwa-server || true
            
            sudo docker run -d --name meanhwa-server -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE="prod" \
              -e DB_URL="$DB_URL" \
              -e DB_USERNAME="$DB_USERNAME" \
              -e DB_PASSWORD="$DB_PASSWORD" \
              "$DOCKERHUB_USERNAME/meanhwa-back"
